[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; ==========================
; Compiler | Language
; ==========================
build_unflags = -std=gnu++11 ; get rid of old cpp standard flags
build_flags =
    -std=gnu++20
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -Wformat=2
    -Wno-unused-parameter
    -Wno-unused-variable
    -O2
    ;-DUSB_SERIAL             ; Teensy USB mode
    ;-DTEENSY_OPT_FAST=1      ; Teensy-specific speed option

; ==========================
; For Clangd || IntelliSense
; ==========================
; Generate compile_commands.json for your beloved clangd uwu~
extra_scripts = 
    pre:generate_compile_commands.py

; ==========================
; Libraries
; ==========================
lib_deps =
    paulstoffregen/Encoder @ ^1.4.1
    adafruit/Adafruit BusIO @ ^1.14.4
    ; Add libs later if needed

; ==========================
; Upload behavior
; ==========================
;upload_protocol = teensy-cli

; ==========================
; folder structure overrides
; ==========================
src_dir = src
include_dir = include
lib_dir = lib
