[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_ldf_mode = chain+

; ==========================
; Compiler | Language
; ==========================
build_unflags =
    -std=gnu++17
    -fno-exceptions
    -fno-rtti
    -fno-threadsafe-statics
    -nostdlib

build_flags =
    -std=gnu++20
    -lstdc++
    -O2
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -frtti
    ;-fexceptions
    -fthreadsafe-statics
    -DARDUINO_TEENSY41
    -I$PROJECT_PACKAGES_DIR/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include/c++
    -I$PROJECT_PACKAGES_DIR/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include/c++/11.3.1
    -I$PROJECT_PACKAGES_DIR/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include

; ==========================
; For Clangd || IntelliSense
; ==========================
; Generate compile_commands.json for your beloved clangd uwu~
extra_scripts = 
    pre:generate_compile_commands.py

; ==========================
; Libraries
; ==========================
lib_deps =
    paulstoffregen/Encoder @ ^1.4.1
    adafruit/Adafruit BusIO @ ^1.14.4
    ; StandardCplusplus
    ; Add libs later if needed

; ==========================
; Upload behavior
; ==========================
;upload_protocol = teensy-cli

; ==========================
; folder structure overrides
; ==========================
;src_dir = src
;include_dir = include
;lib_dir = lib
