[platformio]
; src_dir = src
include_dir = include
lib_dir = lib

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_ldf_mode = chain+

; ==========================
; Compiler | Language
; ==========================
build_unflags =
    -std=gnu++17
    -fno-rtti
    -fno-threadsafe-statics
    -nostdlib

build_flags =
    -std=gnu++20
    -lstdc++
    -O2
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -frtti
    ;-fexceptions
    -fthreadsafe-statics
    -DARDUINO_TEENSY41
    -isystem$PROJECT_PACKAGES_DIR/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include/c++/11.3.1
    -isystem$PROJECT_PACKAGES_DIR/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include/c++/11.3.1/arm-none-eabi
    -isystem$PROJECT_PACKAGES_DIR/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include

; ==========================
; For Clangd || IntelliSense
; ==========================
; Generate compile_commands.json
extra_scripts =  pre:generate_compile_commands.py

; ==========================
; Libraries
; ==========================
lib_deps =
    fmtlib/fmt @ ^8.1.1
    ; StandardCplusplus
    ; Add libs later if needed

; ==========================
; folder structure overrides
; ==========================
build_src_filter = +<teensy/>



[env:esp32s3camlcd]
platform = espressif32
board = esp32s3camlcd
framework = arduino
lib_ldf_mode = chain+

monitor_speed = 115200

; ==========================
; Compiler | Language
; ==========================
build_unflags =
    -std=gnu++17
    -fno-rtti
    -fno-threadsafe-statics
    -nostdlib

build_flags =
    -std=gnu++2a
    -lstdc++
    -O2
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -frtti
    -fexceptions
    -fthreadsafe-statics

; ==========================
; For Clangd || IntelliSense
; ==========================
; Generate compile_commands.json
extra_scripts = pre:generate_compile_commands.py

; ==========================
; Libraries
; ==========================
lib_deps =
    fmtlib/fmt @ ^8.1.1
    ; Add libs later if needed

; ==========================
; folder structure overrides
; ==========================
build_src_filter = +<esp/>
